// flow-typed signature: 46ce873b2c845ee0f518b717f89eef7b
// flow-typed version: <<STUB>>/connected-react-router_v6.3.1/flow_v0.95.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'connected-react-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'connected-react-router' {
  import type { Middleware, Reducer } from 'redux';
  import type { BrowserHistory } from 'history/createBrowserHistory';

  declare export var LOCATION_CHANGE: '@@router/LOCATION_CHANGE';

  declare export function routerMiddleware<S, A, D>(history: BrowserHistory): Middleware<S, A, D>;
  declare export function connectRouter<S, A>(history: BrowserHistory): Reducer<S, A>;
  declare export function push<A>(url: string): A;

  declare export class ConnectedRouter<BrowserHistory> extends React$Component<{
    history: BrowserHistory,
    children?: React$Node,
  }> {}
}
